on:
  push:
    branches:
      - main

env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: greenspace-webapi-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: greenspace
  RESOURCE_GROUP: DefaultResourceGroup-SEA
  CONTAINER_REGISTRY_NAME: registry20250410065218
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20250410065218.azurecr.io

jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.greenspace_SPN }}

      - name: Deploy Container App (image only)
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
          acrUsername: ${{ secrets.registry20250410065218_USERNAME_35CD }}
          acrPassword: ${{ secrets.registry20250410065218_PASSWORD_35CD }}
          imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}

      - name: Set connection string via az CLI 
        run: |
            az containerapp update \
              --name ${{ env.CONTAINER_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --set-env-vars \
                ConnectionStrings__DefaultConnection="${{ secrets.DEFAULT_CONNECTION }}" \
                ConnectionStrings__MongoDbConnection="${{ secrets.MONGO_CONNECTION }}" \
                JWTOptions__Issuer=green-space \
                JWTOptions__Audience=green-space-client \
                JWTOptions__Secret="${{ secrets.JWT_SECRET }}" \
                CloudinarySettings__CloudName="${{ secrets.CLOUD_NAME }}" \
                CloudinarySettings__ApiKey="${{ secrets.CLOUD_APIKEY }}" \
                CloudinarySettings__ApiSecret="${{ secrets.CLOUD_APISECRET }}" \
                GHN__ShopId="${{ secrets.GHN_SHOPID }}" \
                GHN__Token="${{ secrets.GHN_TOKEN }}" \
                FirebaseSettings__ApiKeY="${{ secrets.FIREBASE_APIKEY }}" \
                FirebaseSettings__AuthEmail="${{ secrets.FIREBASE_EMAIL }}" \
                FirebaseSettings__AuthPassword="${{ secrets.FIREBASE_PASSWORD }}" \
                VnPay__Vnp_TmnCode="${{ secrets.VNP_TMNCODE }}" \
                VnPay__Vnp_HashSecret="${{ secrets.VNP_HASHSECRET }}" \
                ASPNETCORE_ENVIRONMENT=Production 