name: Trigger auto deployment for greenspace-webapi-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/greenspace-webapi-container-app-AutoDeployTrigger-a78e613b-e399-4ab5-9fa8-aebbf7b643e3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GREENSPACEWEBAPICONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GREENSPACEWEBAPICONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GREENSPACEWEBAPICONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: registry20250410065218.azurecr.io
          registryUsername: ${{ secrets.GREENSPACEWEBAPICONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GREENSPACEWEBAPICONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: greenspace-webapi-container-app
          resourceGroup: DefaultResourceGroup-SEA
          imageToBuild: registry20250410065218.azurecr.io/greenspace-webapi-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


